version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    command: --innodb-buffer-pool-size=50M --innodb-log-buffer-size=8M --innodb-flush-log-at-trx-commit=2 --innodb-file-per-table=1 --max-connections=25
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: reco123!..
      MYSQL_MAX_CONNECTIONS: 25
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 1000000000
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: